In [1]:
# Importing dependencies

from learntools.core import binder
import numpy as np

binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10?

In [12]:
def question_1():
    arr = np.arange(5,905,10)
    return arr

q1_sol = question_1()
q1.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [30]:
def question_2():
    arr = list(range(5,905,10))
    numpy_arr = np.array(arr)
    return numpy_arr
    raise NotImplementedError
    

q2_sol = question_2()
q2.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [31]:
import string 
def question_3():
    capital_letters_arr = np.array(list(string.ascii_uppercase))
    return capital_letters_arr
    raise NotImplementedError


q3_sol = question_3()
q3.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [39]:
def question_4() -> tuple:
    # Expected: return (sol1, sol2)
    arr_ten_zeros = np.zeros(10)
    arr_six_ones = np.ones(6)
    return (arr_ten_zeros,arr_six_ones)
    raise NotImplementedError

q4.hint()
q4_sol_1, q4_sol_2 = question_4()
q4.check()

<IPython.core.display.Javascript object>

<span style="color:#3366cc">Hint:</span> Use np.zeros and np.ones to create the arrays and return them as a tuple.

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q5**: Given an 2-D array, print the third column.

In [5]:
input = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])


def question_5(input):
    arr_third_column = input[0:3, 2]
    print(arr_third_column)
    return arr_third_column
    raise NotImplementedError

q5_sol = question_5(input)
q5.check()

[33 66 99]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [3]:
def question_6():
    arr_12_zeros = np.zeros((3,4), dtype=np.int64)
    return arr_12_zeros
    raise NotImplementedError


q6_sol = question_6()
q6.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [14]:
input = np.arange(7, 34, 1).reshape(9, 3)


def question_7(input):
    # Expected: return (q7_sol_1, q7_sol_2, q7_sol_3)
    arr = np.split(input,3)
    return arr
    raise NotImplementedError


q7_sol_1, q7_sol_2, q7_sol_3 = question_7(input)
q7.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q8**: Return the last 2 elements by each of the first rows of the (3,4) array. 

In [14]:
input = np.arange(1, 13, 1).reshape(3, 4)

def question_8(input):
    two_last_ele = input[0:2,2:4]
    print(two_last_ele)
    return two_last_ele
    raise NotImplementedError


q8_sol = question_8(input)
q8.check()


[[3 4]
 [7 8]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q9**: Return how many elements are greater than 5 in an array.

In [21]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_9(input):
    bool_mask = input > 5
    print(bool_mask)
    total = np.sum(bool_mask)
    print(total)
    return total
    raise NotImplementedError


q9_sol = question_9(input)
q9.check()

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
7


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [25]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])


def question_10(input, insert_data):
    input = np.delete(input, 1, 1)
    input_change = np.insert(input, 1, insert_data, 1)
    return input_change
    raise NotImplementedError

q10_sol = question_10(input, insert_data)
q10.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [3]:
input = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])

def question_11(input):
    print(np.diff(input, axis=0))
    distance = np.sqrt(np.sum(np.diff(input, axis=0)**2, axis=1))
    distance_with_nan = np.append(distance, 0).reshape(4, 1)
    result = np.hstack((input, distance_with_nan))
    print(result)
    return result
    raise NotImplementedError

q11_sol = question_11(input)
q11.check()

[[3 4]
 [3 2]
 [3 2]]
[[ 1.          2.          5.        ]
 [ 4.          6.          3.60555128]
 [ 7.          8.          3.60555128]
 [10.         10.          0.        ]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q12**: Remove consecutive duplicates from a NumPy array.

In [20]:
input = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])


def question_12(input):
    for i in range(len(input)-2):
        if (np.array_equal(input[i], input[i+1])):
            input = np.delete(input, i+1, axis=0)
    return input
    raise NotImplementedError

q12_sol = question_12(input)
q12.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [10]:
input = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])


def question_13(input):
    mean = np.mean(input, axis=0)
    print(mean)
    std = np.std(input, axis=0)
    print(std)
    for i in range(len(std)):
        if std[i] == 0:
            std[i] = 1
    normalized = (input - mean) / std
    return normalized
    raise NotImplementedError


q13_sol = question_13(input)
q13.check()

[11.75 21.   31.  ]
[2.86138079 2.23606798 1.58113883]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [23]:
input = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



def question_14(input):
    sum = np.sum(input, axis=1).reshape(1,3)
    input = np.delete(input, 1, axis=1)
    print(input)
    new_arr=np.insert(input, 1, sum, axis=1)
    print(new_arr)
    return new_arr
    raise NotImplementedError


q14_sol = question_14(input)
q14.check()

[[1 3]
 [4 6]
 [7 9]]
[[ 1  6  3]
 [ 4 15  6]
 [ 7 24  9]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [43]:
input = np.array(["hello", "world", "numpy", "rocks"])


def question_15(input):
    input = set(np.unique(np.array(list(("".join(input))))))
    return input
    raise NotImplementedError


q15_sol = question_15(input)
q15.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [5]:
input = np.array(["a", "b", "c", "d", "a", "c", "e"])


def question_16(input):
    dict = {str(char): index for index,char in enumerate(np.unique(input))}
    print(dict)
    return dict
    raise NotImplementedError


q16_sol = question_16(input)
q16.check()

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [14]:
input = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]


def question_17(input):
    print(np.concatenate(input, axis=0))
    return np.concatenate(input, axis=0)

    raise NotImplementedError


q17_sol = question_17(input)
q17.check()

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [18]:
input = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}

labels = "hello rocks"



def question_18(input, labels):
    words = labels.split()
    indices = [input[word] for word in words if word in input]
    return np.array(indices)

    raise NotImplementedError


q18_sol = question_18(input, labels)
q18.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [32]:
input = np.array([[3, 4], [0, 0], [-2, 1]])

def question_19(input):
    result = [] 
    difference = np.diff(input, axis=1)
    for i in range(len(difference)):
        if difference[i] != 0:
            result.append(input[i])

    print(np.array(result))
    return np.array(result)
    raise NotImplementedError


q19_sol = question_19(input)
q19.check()

[[ 3  4]
 [-2  1]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
5. Add a Binary Column for Missing Data
- Stack All Features into a Final Matrix
Create a new column `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, moving averages, first-order differences, and the missing flag.

In [69]:
input = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)


def question_20(input):
    # Normalize each sensor reading
    mean = np.mean(input, axis=0)
    std = np.std(input, axis=0)
    
    for i in range(len(std)):
        if std[i] == 0:
            std[i] = 1
    normalized_input = (input - mean) / std
    
    # Replace the value exceed the bounds
    input_copy = input.copy()
    check = np.logical_or(normalized_input > 2.5, normalized_input < -2.5)

    input_copy[check] = np.nan

    # Fill in the zeros with nonzero neighbours
    input_copy_interpolated = input_copy.copy()
    rows, cols = input_copy_interpolated.shape
    for i in range(rows):
        for j in range(cols):
            if input_copy_interpolated[i, j] == 0:  # Check for zero
                # Collect nonzero neighbors
                neighbors = []
                if i > 0 and input_copy_interpolated[i-1, j] != 0:  # Above
                    neighbors.append(input_copy_interpolated[i-1, j])
                if i < rows-1 and input_copy_interpolated[i+1, j] != 0:  # Below
                    neighbors.append(input_copy_interpolated[i+1, j])
                if j > 0 and input_copy_interpolated[i, j-1] != 0:  # Left
                    neighbors.append(input_copy_interpolated[i, j-1])
                if j < cols-1 and input_copy_interpolated[i, j+1] != 0:  # Right
                    neighbors.append(input_copy_interpolated[i, j+1])
                
                # Replace zero with the average of its neighbors
                if len(neighbors) != 0:  # Ensure there are neighbors
                    input_copy_interpolated[i, j] = sum(neighbors) / len(neighbors)

    # Calculate the diff in time
    first_order_diff = np.diff(input_copy, axis = 0)
    first_order_diff_padded = np.vstack(
    (first_order_diff, np.zeros((1, first_order_diff.shape[1])))
    )

    # Add Binary column for missing data
    missing_flag = np.isnan(input_copy).astype(int)

    # Result Matrix by stacking all the interpolated data, first-order differences, and missing flags
    result_matrix = np.hstack(
        (input_copy_interpolated, first_order_diff_padded, missing_flag)
    )

    return result_matrix
    raise NotImplementedError


q20_sol = question_20(input)
q20.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>